import streamlit as st
import os
from src.analyst import run_analysis
from src.coach import run_coach
from src.execution import execute_trade

# Page configuration
st.set_page_config(
    page_title="Bitcoin Trading Coach",
    page_icon="🪙",
    layout="centered"
)

# Title
st.title("🪙 Bitcoin Trading Coach")

# Subtitle/Welcome
st.markdown("""
Welcome to the **Bitcoin Trading Coach** portal. This tool utilizes a 3-agent orchestration system to scan markets, plan risk boundaries, and execute orders safely.
""")

# Initialize Session State to persist data across Streamlit reruns
if "analysis" not in st.session_state:
    st.session_state.analysis = None
if "setup" not in st.session_state:
    st.session_state.setup = None
if "trade_result" not in st.session_state:
    st.session_state.trade_result = None

# Sidebar - Settings & Env info
st.sidebar.header("⚙️ System Status")
env_mode = os.getenv("ENVIRONMENT", "sandbox").lower()
st.sidebar.subheader(f"Active Env: `{env_mode.upper()}`")

if env_mode == "production":
    st.sidebar.warning("⚠️ Running in PRODUCTION mode. Real funds are active!")
else:
    st.sidebar.info("🤖 Running in SANDBOX mode. Real funds are safe.")

# Main Action: Scan Market
st.subheader("1. Market Scanner (Analyst & Coach)")
if st.button("🔍 Scan Market Now", type="primary"):
    with st.spinner("Analyst scanning BTC charts..."):
        # Run Analyst Agent
        analysis = run_analysis()
        if analysis:
            st.session_state.analysis = analysis
            # Run Coach Agent
            setup = run_coach(analysis)
            st.session_state.setup = setup
            # Reset previous trade results
            st.session_state.trade_result = None
            st.success("Market scan completed successfully!")
        else:
            st.error("Error: Analyst Agent was unable to retrieve market data. Check your connection or API logs.")

# Display Scan Results
if st.session_state.analysis and st.session_state.setup:
    analysis = st.session_state.analysis
    setup = st.session_state.setup
    
    st.markdown("---")
    st.subheader("📊 Scan Findings & Trading Plan")
    
    # Metrics columns
    col1, col2, col3 = st.columns(3)
    col1.metric("Current Price", f"${analysis['current_price']:.2f}")
    col2.metric("Support Level", f"${analysis['support_level']:.2f}")
    col3.metric("Resistance Level", f"${analysis['resistance_level']:.2f}")
    
    st.info(f"Market Data Source: **{analysis.get('source', 'Unknown')}**")
    
    # Display Generated Candlestick Chart
    chart_path = "src/coach_chart.png"
    if os.path.exists(chart_path):
        st.image(chart_path, caption="Candlestick Chart with Trade Setup Plan (Generated by Coach Agent)")
    else:
        st.warning("Matplotlib chart image file not found.")
        
    # Trade Setup Breakdown
    st.subheader("💡 Coach Recommendation")
    bias_color = "green" if "BUY" in setup["bias"] else "red"
    st.markdown(f"Proposed Bias: **:{bias_color}[{setup['bias']}]**")
    
    col_e, col_sl, col_tp = st.columns(3)
    col_e.markdown(f"**Entry Target**  \n`${setup['entry']:.2f}`")
    col_sl.markdown(f"**Stop-Loss**  \n`:${bias_color}[${setup['stop_loss']:.2f}]`")
    col_tp.markdown(f"**Take-Profit**  \n`${setup['take_profit']:.2f}`")

    # Execution Gatekeeper Panel
    st.markdown("---")
    st.subheader("🔒 2. Execution Gatekeeper")
    st.markdown("""
    The Execution Agent requires explicit manual confirmation. To authorize order placement, type the word **`CONFIRM`** in the box below and click execute.
    """)
    
    confirm_input = st.text_input("Security Confirmation:", placeholder="Type CONFIRM here to authorize", key="confirm_text")
    
    if st.button("🚀 Execute Trade Order", type="primary"):
        if confirm_input.strip() == "CONFIRM":
            with st.spinner("Execution Agent placing order on Kraken..."):
                direction = "buy" if "BUY" in setup["bias"] else "sell"
                # Executing a small default trade size of 0.01 BTC for sandbox/demo testing
                result = execute_trade(
                    pair="XBTUSD",
                    direction=direction,
                    order_type="limit",
                    volume=0.01,
                    price=setup["entry"],
                    confirm=True
                )
                st.session_state.trade_result = result
        else:
            st.error("Access Denied: You must type exactly **`CONFIRM`** to run the trade.")
            
    # Display Order Result
    if st.session_state.trade_result:
        res = st.session_state.trade_result
        if res.get("status") in ["SUCCESS", "SUCCESS (SIMULATION)"]:
            st.success(f"🎉 Order placed! Status: {res['status']}")
            st.json(res)
        else:
            st.error(f"❌ Order failed: {res.get('error', 'Unknown Error')}")
