import streamlit as st
import os
from src.analyst import run_analysis
from src.coach import run_coach, answer_coach_question
from src.execution import execute_trade

# 1. Initialize wide layout at the very top
st.set_page_config(
    page_title="BTC Trading Coach Terminal",
    page_icon="🪙",
    layout="wide"
)

# Custom css for a high-end trading terminal look
st.markdown("""
<style>
    .terminal-header {
        font-family: 'Courier New', Courier, monospace;
        color: #00ffcc;
        text-shadow: 0 0 10px rgba(0, 255, 204, 0.5);
    }
    .status-card {
        padding: 15px;
        border-radius: 5px;
        background-color: #1e222b;
        border: 1px solid #2e323d;
        font-family: 'Courier New', Courier, monospace;
    }
</style>
""", unsafe_allow_html=True)

# Application Header
st.markdown('<h1 class="terminal-header">🪙 BTC TRADING COACH TERMINAL v2.0</h1>', unsafe_allow_html=True)
st.markdown("---")

# Session State Persistence
if "analysis" not in st.session_state:
    st.session_state.analysis = None
if "setup" not in st.session_state:
    st.session_state.setup = None
if "trade_result" not in st.session_state:
    st.session_state.trade_result = None

# Sidebar Configuration
st.sidebar.markdown('<h2 class="terminal-header">⚙️ CORE CONTROL</h2>', unsafe_allow_html=True)
env_mode = os.getenv("ENVIRONMENT", "sandbox").lower()
st.sidebar.markdown(f"ENVIRONMENT: **`{env_mode.upper()}`**")

if env_mode == "production":
    st.sidebar.error("🚨 LIVE TRADING ACTIVE - REAL FUNDS")
else:
    st.sidebar.info("🤖 SANDBOX MODE ACTIVE - MOCK TRADING")

# 2. Primary Action Button Container
scan_container = st.container()
with scan_container:
    col_btn, col_stats = st.columns([1, 3])
    with col_btn:
        trigger_scan = st.button("⚡ SCAN MARKET NOW", type="primary", use_container_width=True)
        if trigger_scan:
            with st.spinner("Analyst scanning charts..."):
                analysis = run_analysis()
                if analysis:
                    st.session_state.analysis = analysis
                    setup = run_coach(analysis)
                    st.session_state.setup = setup
                    st.session_state.trade_result = None
                    st.success("Scan Complete.")
                else:
                    st.error("Error: Scan failed.")

    with col_stats:
        if st.session_state.analysis:
            analysis = st.session_state.analysis
            st.markdown(f"""
            **Current BTC Price:** `${analysis['current_price']:.2f}` | 
            **Support Level:** `${analysis['support_level']:.2f}` | 
            **Resistance Level:** `${analysis['resistance_level']:.2f}` | 
            **Source:** `{analysis.get('source', 'Unknown')}`
            """)
        else:
            st.markdown("*Waiting for market scan. Click 'Scan Market Now' to begin.*")

st.markdown("---")

# 3. 4-Column Row for Strategy Agents
st.subheader("📡 Technical Analysis Strategy Panel")
strat_cols = st.columns(4, border=True)

strategies_def = [
    ("RSI", "Relative Strength Index (Oversold/Overbought)"),
    ("MACD", "Moving Average Convergence/Divergence"),
    ("Volume", "Climax and Rejection Volume Scanner"),
    ("Stair-Step", "Price Action Continuation Patterns")
]

for idx, (strat_name, strat_desc) in enumerate(strategies_def):
    with strat_cols[idx]:
        st.markdown(f"### {strat_name} Agent")
        st.caption(strat_desc)
        
        # Check if we have active signals from a scan
        if st.session_state.analysis and "strategy_signals" in st.session_state.analysis:
            sig_data = st.session_state.analysis["strategy_signals"].get(strat_name, {})
            signal = sig_data.get("signal", "NEUTRAL")
            details = sig_data.get("details", "")
            
            # Format signal colors
            if signal == "BUY":
                st.success("🟢 BUY SIGNAL")
            elif signal == "SELL":
                st.error("🔴 SELL SIGNAL")
            else:
                st.info("⚪ NEUTRAL")
                
            st.caption(details)
        else:
            # 4. Placeholder blocks
            st.metric(label="Signal Status", value="OFFLINE", delta=None)
            st.caption("Waiting for market scanner execution...")

st.markdown("---")

# 5. Wider Section for Coach Visuals and Explanations
if st.session_state.analysis and st.session_state.setup:
    analysis = st.session_state.analysis
    setup = st.session_state.setup
    
    st.subheader("💡 Coach Agent Risk Assessment")
    
    # Split into 2 columns: Chart on left, Text explanation on right
    col_chart, col_explain = st.columns([2, 1])
    
    with col_chart:
        chart_path = "src/coach_chart.png"
        if os.path.exists(chart_path):
            st.image(chart_path, caption="Candlestick Chart with Trade Setup Plan (Generated by Coach Agent)")
        else:
            st.warning("Matplotlib chart image file not found.")
            
        st.markdown("---")
        st.subheader("💬 Ask the Coach")
        user_question = st.text_input("Ask the Coach a question about this setup:", placeholder="e.g., Why did the MACD signal neutral? / Why is the Stop-Loss placed there?")
        if user_question:
            with st.spinner("Coach is thinking..."):
                answer = answer_coach_question(user_question, analysis, setup)
                st.markdown(f"**Coach Response:**")
                st.info(answer)
            
    with col_explain:
        bias_color = "green" if "BUY" in setup["bias"] else "red"
        st.markdown(f"### Proposed Bias: **:{bias_color}[{setup['bias']}]**")
        
        st.markdown("#### Plan Boundaries:")
        st.write(f"🟢 **Entry Target**: `${setup['entry']:.2f}`")
        st.write(f"🔴 **Stop-Loss**: `${setup['stop_loss']:.2f}`")
        st.write(f"🔵 **Take-Profit**: `${setup['take_profit']:.2f}`")
        
        st.divider()
        
        # Display detailed Coach logic explanation (Tutoring aid)
        st.markdown("#### Coaching Explanation:")
        if "BUY" in setup["bias"]:
            explanation = (
                "The current price is located in the **lower half** of our identified trading range "
                f"(${analysis['support_level']:.2f} - ${analysis['resistance_level']:.2f}). "
                "Since price is closer to the support level, a buying opportunity presents a highly favorable "
                "Risk-to-Reward ratio. The Stop-Loss is positioned 1.5% below support to allow room for minor "
                "fakeouts, while the Take-Profit is set just below major resistance."
            )
        else:
            explanation = (
                "The current price is located in the **upper half** of our identified trading range "
                f"(${analysis['support_level']:.2f} - ${analysis['resistance_level']:.2f}). "
                "Since price is closer to the resistance level, buying is unfavorable. Instead, a short/sell setup "
                "is proposed. The Stop-Loss is placed 1.5% above major resistance to protect capital, and the "
                "Take-Profit target is aligned near the support level."
            )
        st.info(explanation)
        
    # Execution Panel
    st.markdown("---")
    st.subheader("🔒 3. Execution Gatekeeper Panel")
    st.markdown("""
    The Execution Agent requires explicit manual confirmation. To authorize order placement, enter your unique cryptographic passphrase below.
    """)
    
    col_input, col_action = st.columns([2, 1])
    with col_input:
        passphrase_input = st.text_input("Security Passphrase:", type="password", placeholder="Enter your trade passphrase to authorize", key="trade_passphrase_input")
    with col_action:
        st.write(" ") # Padding
        st.write(" ") # Padding
        execute_btn = st.button("🚀 Execute Trade Order", type="primary", use_container_width=True)
        
    if execute_btn:
        with st.spinner("Execution Agent placing order on Kraken..."):
            direction = "buy" if "BUY" in setup["bias"] else "sell"
            result = execute_trade(
                pair="XBTUSD",
                direction=direction,
                order_type="limit",
                volume=0.01,
                price=setup["entry"],
                passphrase=passphrase_input
            )
            st.session_state.trade_result = result
            
    # Display Order Result
    if st.session_state.trade_result:
        res = st.session_state.trade_result
        if res.get("status") in ["SUCCESS", "SUCCESS (SIMULATION)"]:
            st.success("🎉 Trade Authorized and Sent to Kraken Testnet")
            st.json(res)
        else:
            st.error(f"❌ {res.get('error', 'Unknown Error')}")
else:
    st.info("Run a market scan above to view the risk assessment chart, coaching explanation, and execution options.")
